### ISSUE TITLE
Object.basename is deprecated.

### ISSUE THREAD

**Issue by sbrowne217828** [Kerosene2000/atom-header-42#12] opened 2017-11-26 02:51 UTC
Arguments to `path.basename` must be strings
```
Object.basename (C:\Users\sbrow\AppData\Local\atom\app-1.21.1\resources\app.asar\src\electron-shims.js:31:10)
Object.getHeader (C:\Users\sbrow\.atom\packages\header-42\lib\header-42.coffee:89:23)
Object.insert (C:\Users\sbrow\.atom\packages\header-42\lib\header-42.coffee:129:21)
HTMLElement.subscriptions.add.atom.commands.add.header-42:insert (C:\Users\sbrow\.atom\packages\header-42\lib\header-42.coffee:52:26)
CommandRegistry.handleCommandEvent (<embedded>:22450:36)
KeymapManager.dispatchCommandEvent (<embedded>:68200:22)
```

**Comment by Kerollmops** [comment] 2017-11-26 07:46
duplicate of https://github.com/Kerollmops/atom-header-42/issues/13

**Closed as completed by Kerollmops** 2017-11-26 07:46 UTC
